### ISSUE TITLE
Fix and test motor functions

### ISSUE THREAD

**Issue by tcorbly** [kipr/2D-Simulator#6]
- [x] clear_motor_position counter
- [x] ao
- [x] move_to_position

**Comment by prithvirajkadiyala** [comment]
Do we clear_motor_position on reset?

**Comment by prithvirajkadiyala** [comment]
Change the ao() to set motor power to 0 rather than setting the motor mode to 0.
Because the motor() call sets the motor mode to forward when called.

**Comment by prithvirajkadiyala** [comment]
JavaScript processing the bitwise operations on base 16 values. We will need it to process base 2 values. ao() will work when we move the bases from 16 to 2

**Comment by prithvirajkadiyala** [comment]
Fixed it by calling motor(port, 0) in libwallaby

**Comment by prithvirajkadiyala** [comment]
Fix the clear_motor_position_counter by adding EMJS code to set registers to zeros in this line here.
https://github.com/kipr/libwallaby/blob/c9cac3c446bd02bcb422515e2986a956d62d749a/src/motors_c.cpp#L28
